CREATE USER IF NOT EXISTS 'Admin'@'%' IDENTIFIED BY 'Admin';
GRANT ALL PRIVILEGES ON blog_nelson.* TO 'Admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    posicion VARCHAR(100) NOT NULL,
    posicion2 VARCHAR(100),
    numero INT NOT NULL,
    equipo VARCHAR(100) NOT NULL,
    descripcion TEXT NOT NULL,
    imagen TEXT NOT NULL,
    supertecnica VARCHAR(100) NOT NULL
);
